export const HEARTBEAT_INTERVAL_MS = 60_000;
export const HEARTBEAT_TIMEOUT_MS = 180_000;
export const STUDENT_DASHBOARD_POLLING_MS = 10_000;
export const TEACHER_DASHBOARD_POLLING_MS = 10_000;

export const HEARTBEAT_TIMEOUT_MINUTES = HEARTBEAT_TIMEOUT_MS / 60_000;
