export const MAIN_STUDY_ROOM_LABEL = "메인룸";
export const QUESTION_ROOM_LABEL = "1:1룸";
export const INTERNAL_FALLBACK_ROOM_LABEL = "내부";

export const MAIN_STUDY_LOGICAL_SPACE_KEY = "MAIN_STUDY";
export const QUESTION_POOL_LOGICAL_SPACE_KEY = "QUESTION_POOL";
